# generated by PyScadeOne Wrapper 1.0

from pathlib import Path
import ctypes
from enum import Enum

# load the SCADE executable code
_lib_path = Path(__file__).parent / "root_wrapper.dll"
_lib = ctypes.cdll.LoadLibrary(str(_lib_path))

class EnumType(Enum):
    def __str__(self) -> str:
        return self.name


class SSM_ST_SSM2(Enum):
    SSM_st_cc_active_SSM2 = 0
    SSM_st_cc_standby_SSM2 = 1


class SSM_ST_SSM1(Enum):
    SSM_st_cc_disabled_SSM1 = 0
    SSM_st_cc_enabled_SSM1 = 1



def _ctypes_array2tuple(value: ctypes.Array) -> tuple:
    if not isinstance(value, ctypes.Array):
        raise TypeError("Expected a ctypes.Array")
    return tuple(_ctypes_array2tuple(item) if isinstance(item, ctypes.Array) else item for item in value)


# operator inputs
class cruise_control_CC_design_Inputs:
    def __init__(self) -> None:
        self._v_speed: float = 0.0
        self._brake: float = 0.0
        self._accel: float = 0.0
        self._on: bool = False
        self._res: bool = False
        self._set_point: float = 0.0

    @property
    def v_speed(self) -> float:
        return self._v_speed

    @v_speed.setter
    def v_speed(self, value: float) -> None:
        self._v_speed = value


    @property
    def brake(self) -> float:
        return self._brake

    @brake.setter
    def brake(self, value: float) -> None:
        self._brake = value


    @property
    def accel(self) -> float:
        return self._accel

    @accel.setter
    def accel(self, value: float) -> None:
        self._accel = value


    @property
    def on(self) -> bool:
        return bool(self._on)

    @on.setter
    def on(self, value: bool) -> None:
        self._on = True if value else False


    @property
    def res(self) -> bool:
        return bool(self._res)

    @res.setter
    def res(self, value: bool) -> None:
        self._res = True if value else False


    @property
    def set_point(self) -> float:
        return self._set_point

    @set_point.setter
    def set_point(self, value: float) -> None:
        self._set_point = value


# operator outputs
class cruise_control_CC_design_Outputs:
    def __init__(self) -> None:
        self._throttle = ctypes.c_float(0.0)

    @property
    def throttle(self) -> float:
        return self._throttle.value


class cruise_control_CC_design:
    def __init__(self) -> None:
        alloc_fct = _lib.py_alloc_cruise_control_CC_design
        alloc_fct.argtypes = []
        alloc_fct.restype = ctypes.c_void_p
        context = alloc_fct()
        self._out_c = ctypes.c_void_p.from_address(context)
        self.reset_fct = _lib.cruise_control_reset_CC_design
        self.reset_fct.restype = ctypes.c_void_p
        self.cycle_fct = _lib.cruise_control_CC_design
        self.cycle_fct.argtypes = [
            ctypes.c_float,
            ctypes.c_float,
            ctypes.c_float,
            ctypes.c_uint8,
            ctypes.c_uint8,
            ctypes.c_float,
            ctypes.POINTER(ctypes.c_float),
            ctypes.POINTER(ctypes.c_void_p),
        ]
        self.cycle_fct.restype = ctypes.c_void_p
        self.inputs = cruise_control_CC_design_Inputs()
        self.outputs = cruise_control_CC_design_Outputs()

    def __del__(self):
        free_fct = _lib.py_free_cruise_control_CC_design
        free_fct.argtypes = [ctypes.c_void_p]
        free_fct.restype = None
        free_fct(ctypes.byref(self._out_c))

    def reset(self) -> None:
        self.reset_fct(ctypes.byref(self._out_c))

    def cycle(self, cycles: int = 1) -> None:
        for i in range(cycles):
            self.cycle_fct(
                self.inputs._v_speed,
                self.inputs._brake,
                self.inputs._accel,
                self.inputs._on,
                self.inputs._res,
                self.inputs._set_point,
                ctypes.byref(self.outputs._throttle),
                ctypes.byref(self._out_c),
            )

# end of file