/* generated by PyScadeOne Wrapper 1.0 */

#include <stdlib.h>
    
#include "cruise_control_CC_design.h"



/* CC_design::cruise_control */
__declspec(dllexport) void* py_alloc_cruise_control_CC_design()
{
    outC_cruise_control_CC_design *ctx = (outC_cruise_control_CC_design*)malloc(sizeof(outC_cruise_control_CC_design));
    cruise_control_init_CC_design(ctx);
    return (void*)ctx;
}

__declspec(dllexport) void py_free_cruise_control_CC_design(void *ctx)
{
    if (ctx != 0)
        free(ctx);
}

/* end of file */