# test_limiter.py
# Tests the generated limiter operator against REQ-LIM-01..03.
# Mirrors the 3 manual simulation steps from Activity 2F.
#
# Run setup_wrapper.py first to generate limiter_wrapper/limiter_wrapper.py.
#
# By default this looks for limiter_wrapper/ next to this script (the
# solution/starter layout). To test your own generated project instead —
# e.g. after copying/uploading your own blocks.swan + generated wrapper
# into a different folder — pass --project-dir:
#   python test_limiter.py --project-dir path\to\your\project
#
# This is the simple version: cycle the operator, print PASS/FAIL. For a
# requirement-traceability report plus a CSV/diagram of which requirements
# pass or fail on the model, see test_limiter_advanced.py.

import argparse
import sys
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--project-dir", "-d", type=Path, default=Path(__file__).parent,
                     help="Folder containing limiter_wrapper/ (default: this script's folder)")
args = parser.parse_args()

# Add the generated wrapper folder to the path
sys.path.insert(0, str(args.project_dir / "limiter_wrapper"))
from limiter_wrapper import limiter_blocks  # type: ignore  # generated by setup_wrapper.py

lim = limiter_blocks()

test_cases = [
    # (value_in, min, max, expected_out, req)
    ( 5.0,  0.0, 10.0,  5.0, "REQ-LIM-03"),   # pass-through
    (20.0,  0.0, 10.0, 10.0, "REQ-LIM-01"),   # clamp at max
    (-5.0,  0.0, 10.0,  0.0, "REQ-LIM-02"),   # clamp at min
]

print("=" * 60)
print("  LIMITER TEST REPORT")
print("=" * 60)

all_passed = True
for value_in, min_v, max_v, expected, req in test_cases:
    lim.reset()
    lim.inputs.value_in = value_in  # inputs via .inputs.<name>
    lim.inputs.min      = min_v
    lim.inputs.max      = max_v
    lim.cycle()
    result = lim.outputs.value_out  # outputs via .outputs.<name>
    status = "PASS" if abs(result - expected) < 1e-9 else "FAIL"
    if status == "FAIL":
        all_passed = False
    print(f"  [{req:10s}] in={value_in:6.1f}  min={min_v:.1f}  max={max_v:.1f}"
          f"  → expected={expected:.1f}  got={result:.1f}  {status}")

print("-" * 60)
print("  ALL PASS" if all_passed else "  SOME TESTS FAILED")
print("=" * 60)
