# generated by PyScadeOne Wrapper 1.0

from pathlib import Path
import ctypes

# load the SCADE executable code
_lib_path = Path(__file__).parent / "counter_wrapper.dll"
_lib = ctypes.cdll.LoadLibrary(str(_lib_path))


def _ctypes_array2tuple(value: ctypes.Array) -> tuple:
    if not isinstance(value, ctypes.Array):
        raise TypeError("Expected a ctypes.Array")
    return tuple(_ctypes_array2tuple(item) if isinstance(item, ctypes.Array) else item for item in value)


# operator inputs
class counter_blocks_Inputs:
    def __init__(self) -> None:
        self._init_value: int = 0
        self._step: int = 0

    @property
    def init_value(self) -> int:
        return self._init_value

    @init_value.setter
    def init_value(self, value: int) -> None:
        self._init_value = value


    @property
    def step(self) -> int:
        return self._step

    @step.setter
    def step(self, value: int) -> None:
        self._step = value


# operator outputs
class counter_blocks_Outputs:
    def __init__(self) -> None:
        self._count = ctypes.c_int32(0)

    @property
    def count(self) -> int:
        return self._count.value


class counter_blocks:
    def __init__(self) -> None:
        alloc_fct = _lib.py_alloc_counter_blocks
        alloc_fct.argtypes = []
        alloc_fct.restype = ctypes.c_void_p
        context = alloc_fct()
        self._out_c = ctypes.c_void_p.from_address(context)
        self.reset_fct = _lib.counter_reset_blocks
        self.reset_fct.restype = ctypes.c_void_p
        self.cycle_fct = _lib.counter_blocks
        self.cycle_fct.argtypes = [
            ctypes.c_int32,
            ctypes.c_int32,
            ctypes.POINTER(ctypes.c_int32),
            ctypes.POINTER(ctypes.c_void_p),
        ]
        self.cycle_fct.restype = ctypes.c_void_p
        self.inputs = counter_blocks_Inputs()
        self.outputs = counter_blocks_Outputs()

    def __del__(self):
        free_fct = _lib.py_free_counter_blocks
        free_fct.argtypes = [ctypes.c_void_p]
        free_fct.restype = None
        free_fct(ctypes.byref(self._out_c))

    def reset(self) -> None:
        self.reset_fct(ctypes.byref(self._out_c))

    def cycle(self, cycles: int = 1) -> None:
        for i in range(cycles):
            self.cycle_fct(
                self.inputs._init_value,
                self.inputs._step,
                ctypes.byref(self.outputs._count),
                ctypes.byref(self._out_c),
            )

# end of file