# test_limiter.py
# Tests the generated limiter operator.
# Mirrors the 3 manual simulation steps from Activity 2D.
#
# Run setup_wrapper.py first to generate limiter_wrapper/limiter_wrapper.py

import sys
from pathlib import Path

# Add the generated wrapper folder to the path
sys.path.insert(0, str(Path(__file__).parent / "limiter_wrapper"))
from limiter_wrapper import limiter_blocks  # type: ignore  # generated by setup_wrapper.py

lim = limiter_blocks()

test_cases = [
    # (value_in, min_value, max_value, expected_out)
    ( 5.0,  0.0, 10.0,  5.0),   # pass-through
    (20.0,  0.0, 10.0, 10.0),   # clamp at max
    (-5.0,  0.0, 10.0,  0.0),   # clamp at min
]

print("=" * 55)
print("  LIMITER TEST REPORT")
print("=" * 55)

all_passed = True
for value_in, min_v, max_v, expected in test_cases:
    lim.reset()
    lim.inputs.value_in = value_in  # inputs via .inputs.<name>
    lim.inputs.min      = min_v
    lim.inputs.max      = max_v
    lim.cycle()
    result = lim.outputs.value_out  # outputs via .outputs.<name>
    status = "PASS" if abs(result - expected) < 1e-9 else "FAIL"
    if status == "FAIL":
        all_passed = False
    print(f"  in={value_in:6.1f}  min={min_v:.1f}  max={max_v:.1f}"
          f"  → expected={expected:.1f}  got={result:.1f}  {status}")

print("-" * 55)
print("  ALL PASS" if all_passed else "  SOME TESTS FAILED")
print("=" * 55)
