# generated by PyScadeOne Wrapper 1.0

from pathlib import Path
import ctypes

# load the SCADE executable code
_lib_path = Path(__file__).parent / "limiter_wrapper.dll"
_lib = ctypes.cdll.LoadLibrary(str(_lib_path))


def _ctypes_array2tuple(value: ctypes.Array) -> tuple:
    if not isinstance(value, ctypes.Array):
        raise TypeError("Expected a ctypes.Array")
    return tuple(_ctypes_array2tuple(item) if isinstance(item, ctypes.Array) else item for item in value)


# operator inputs
class limiter_blocks_Inputs:
    def __init__(self) -> None:
        self._value_in: float = 0.0
        self._min: float = 0.0
        self._max: float = 0.0

    @property
    def value_in(self) -> float:
        return self._value_in

    @value_in.setter
    def value_in(self, value: float) -> None:
        self._value_in = value


    @property
    def min(self) -> float:
        return self._min

    @min.setter
    def min(self, value: float) -> None:
        self._min = value


    @property
    def max(self) -> float:
        return self._max

    @max.setter
    def max(self, value: float) -> None:
        self._max = value


# operator outputs
class limiter_blocks_Outputs:
    def __init__(self) -> None:
        self._value_out = ctypes.c_double(0.0)

    @property
    def value_out(self) -> float:
        return self._value_out


class limiter_blocks:
    def __init__(self) -> None:
        self.cycle_fct = _lib.limiter_blocks
        self.cycle_fct.argtypes = [
            ctypes.c_double,
            ctypes.c_double,
            ctypes.c_double,
        ]
        self.cycle_fct.restype = ctypes.c_double
        self.inputs = limiter_blocks_Inputs()
        self.outputs = limiter_blocks_Outputs()

    def reset(self) -> None:
        # no reset function
        pass

    def cycle(self, cycles: int = 1) -> None:
        for i in range(cycles):
            self.outputs._value_out = self.cycle_fct(
                self.inputs._value_in,
                self.inputs._min,
                self.inputs._max,
            )

# end of file