/* generated by PyScadeOne Wrapper 1.0 */

#include <stdlib.h>
    
#include "main_CC_design.h"



/* CC_design::main */
__declspec(dllexport) void* py_alloc_main_CC_design()
{
    outC_main_CC_design *ctx = (outC_main_CC_design*)malloc(sizeof(outC_main_CC_design));
    main_init_CC_design(ctx);
    return (void*)ctx;
}

__declspec(dllexport) void py_free_main_CC_design(void *ctx)
{
    if (ctx != 0)
        free(ctx);
}

/* end of file */